name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  unit-test:
    runs-on: self-hosted
    container:
      image: cuaesd/aesd-autotest:24-unit-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Grant executable permissions
        run: chmod -R +x .

      - name: Clean build directory
        run: rm -rf ./build

      - name: Configure project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Run unit test
        run: ./unit-test.sh
  full-test:
    runs-on: self-hosted
    container:
      image: cuaesd/aesd-autotest:24-assignment2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Grant executable permissions
        run: chmod -R +x .

      - name: Clean build directory
        run: rm -rf ./build

      - name: Configure project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      - name: Run full test
        run: ./full-test.sh

