name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  unit-test:
    runs-on: self-hosted
    container:
      image: cuaesd/aesd-autotest:24-unit-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set execute permission for unit test
        run: chmod +x ./unit-test.sh

      - name: Run unit test
        run: ./unit-test.sh

  full-test:
    runs-on: self-hosted
    container:
      image: cuaesd/aesd-autotest:24-assignment2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set execute permission for full test
        run: chmod +x ./full-test.sh

      - name: Run full test
        run: ./full-test.sh
